import type { editor } from 'monaco-editor';

export const ENGY_THEME_NAME = 'engy-dark';

export const engyDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [],
  colors: {
    'editor.background': '#09090b',
    'editor.foreground': '#e4e4e7',
    'editor.lineHighlightBackground': '#18181b',
    'editor.selectionBackground': '#3b82f620',
    'editorLineNumber.foreground': '#71717a',
    'editorLineNumber.activeForeground': '#a1a1aa',
    'editorGutter.background': '#09090b',
    'editorCursor.foreground': '#e4e4e7',
    'diffEditor.insertedTextBackground': '#2ea04340',
    'diffEditor.removedTextBackground': '#f8514940',
    'diffEditor.insertedLineBackground': '#2ea04325',
    'diffEditor.removedLineBackground': '#f8514925',
    'editorWidget.background': '#18181b',
    'editorWidget.border': '#27272a',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#27272a80',
    'scrollbarSlider.hoverBackground': '#3f3f4680',
    'scrollbarSlider.activeBackground': '#52525b80',
  },
};

export const ENGY_CYBERPUNK_THEME_NAME = 'engy-cyberpunk';

/** Neon syntax palette matching the cyberpunk flavor's xterm theme. */
export const engyCyberpunkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '8a4a52', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'ff3bd4' },
    { token: 'string', foreground: '00ff9f' },
    { token: 'number', foreground: 'fcee0a' },
    { token: 'regexp', foreground: 'fcee0a' },
    { token: 'type', foreground: '00f0ff' },
    { token: 'class', foreground: '00f0ff' },
    { token: 'interface', foreground: '00f0ff' },
    { token: 'function', foreground: 'ff6b5e' },
    { token: 'variable', foreground: 'ffd9d4' },
    { token: 'constant', foreground: 'fcee0a' },
    { token: 'delimiter', foreground: 'ff5c73' },
    { token: 'tag', foreground: 'ff3bd4' },
    { token: 'attribute.name', foreground: '00f0ff' },
    { token: 'attribute.value', foreground: '00ff9f' },
    // vs-dark defines these narrower scopes itself, and Monaco resolves by
    // specificity — so without an override here the inherited stock colors
    // beat the generic rules above.
    { token: 'string.key.json', foreground: '00f0ff' },
    { token: 'string.value.json', foreground: '00ff9f' },
    { token: 'keyword.json', foreground: 'ff3bd4' },
    { token: 'number.hex', foreground: 'fcee0a' },
    { token: 'string.sql', foreground: '00ff9f' },
    { token: 'keyword.flow', foreground: 'ff3bd4' },
    { token: 'variable.predefined', foreground: 'ff6b5e' },
    { token: 'variable.parameter', foreground: 'ffd9d4' },
    { token: 'delimiter.html', foreground: 'ff5c73' },
    { token: 'delimiter.xml', foreground: 'ff5c73' },
  ],
  colors: {
    'editor.background': '#0d060a',
    'editor.foreground': '#ffd9d4',
    'editor.lineHighlightBackground': '#1a0d14',
    'editor.selectionBackground': '#00f0ff26',
    'editorLineNumber.foreground': '#5c2a3a',
    'editorLineNumber.activeForeground': '#ff5c73',
    'editorGutter.background': '#0d060a',
    'editorCursor.foreground': '#fcee0a',
    'diffEditor.insertedTextBackground': '#00ff9f2e',
    'diffEditor.removedTextBackground': '#ff2a4d33',
    'diffEditor.insertedLineBackground': '#00ff9f1a',
    'diffEditor.removedLineBackground': '#ff2a4d1f',
    'editorWidget.background': '#140a10',
    'editorWidget.border': '#7a2233',
    'editor.findMatchBackground': '#fcee0a4d',
    'editor.findMatchHighlightBackground': '#fcee0a26',
    'editorBracketHighlight.foreground1': '#fcee0a',
    'editorBracketHighlight.foreground2': '#ff3bd4',
    'editorBracketHighlight.foreground3': '#00f0ff',
    'editorBracketHighlight.foreground4': '#00ff9f',
    'editorBracketHighlight.foreground5': '#ff6b5e',
    'editorBracketHighlight.foreground6': '#ff2a4d',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#5c2a3a80',
    'scrollbarSlider.hoverBackground': '#7a2f4480',
    'scrollbarSlider.activeBackground': '#ff2a4d80',
  },
};
