export type {
  WsMessage,
  ClientToServerMessage,
  ServerToClientMessage,
  RegisterMessage,
  WorkspacesSyncMessage,
  ValidatePathsRequestMessage,
  ValidatePathsResponseMessage,
  SearchFilesRequestMessage,
  SearchFilesResponseMessage,
  FileChangeMessage,
  TerminalSpawnCmd,
  TerminalInputCmd,
  TerminalResizeCmd,
  TerminalKillCmd,
  TerminalReconnectCmd,
  TerminalRelayCommand,
  TerminalOutputEvent,
  TerminalExitEvent,
  TerminalReconnectedEvent,
  TerminalErrorEvent,
  TerminalRelayEvent,
} from './ws/protocol.js';
